version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/wineflix
hooks:
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: ec2-user
      timeout: 300
  ApplicationStart:
    - location: scripts/npm-start.sh > /dev/null 2>&1 &
      runas: ec2-user
      timeout: 600